import numpy as np
import matplotlib.pyplot as plt
"""
This script is used to create a glider gun pattern for the Conway's game of life.
The board is a 3D numpy array with the following shape: (x, y, 1). The first two dimensions represent the region 
where the gun is drawn and the third dimension stores the state (alife or dead).
The pattern itself was generated by ChatGPT
The function returns the glider gun and is used in the main program upon calling the draw_pattern function.
The function must be called "create_pattern" and must return the array with the pattern in order to be used.
"""

def create_pattern(): # initiation done by chatGPT
    gun = np.zeros((38,38,1), dtype=int)
    gun[1][25] = 1
    gun[2][23], gun[2][25] = 1, 1
    gun[3][13], gun[3][14], gun[3][21], gun[3][22], gun[3][35], gun[3][36] = 1, 1, 1, 1, 1, 1
    gun[4][12], gun[4][16], gun[4][21], gun[4][22], gun[4][35], gun[4][36] = 1, 1, 1, 1, 1, 1
    gun[5][1], gun[5][2], gun[5][11], gun[5][17], gun[5][21], gun[5][22] = 1, 1, 1, 1, 1, 1
    gun[6][1], gun[6][2], gun[6][11], gun[6][15], gun[6][17], gun[6][18], gun[6][23], gun[6][
        25] = 1, 1, 1, 1, 1, 1, 1, 1
    gun[7][11], gun[7][17], gun[7][25] = 1, 1, 1
    gun[8][12], gun[8][16] = 1, 1
    gun[9][13], gun[9][14] = 1, 1

    gun = np.rot90(gun) # rotate the gun 90 degrees to make it horizontal rather than vertical

    return gun


