"""
This script is used to create the Soba spaceship pattern for the Conway's game of life.
The pattern is a string of dots and 0's. The 0's represent the alive cells and the dots represent the dead cells.
The pattern was retrieved from https://conwaylife.com/wiki/Soba
The function create_pattern() returns the Soba spaceship pattern and is used in the main program upon calling the
draw_pattern function.
The string will be converted to a numpy array in the main program.
"""

pattern = """
........OOO.........OOO........
.......O...O.......O...O.......
......O.O...O.....O...O.O......
......O...OO.......OO...O......
......OOO...O.....O...OOO......
.....O...OO.OOO.OOO.OO...O.....
.....OO..O...OO.OO...O..OO.....
....OOO...OOOOO.OOOOO...OOO....
............O.....O............
.........O...........O.........
....O....O...........O....O....
....O....OOOO.....OOOO....O....
........O....O...O....O........
.......OO.OOO.....OOO.OO.......
.......OO.O...O.O...O.OO.......
...OOO.......OO.OO.......OOO...
..O...OO....O.O.O.O....OO...O..
.O...O...................O...O.
.O.........OOO...OOO.........O.
.....O......OO...OO......O.....
O............O...O............O
O..OO.....O.........O.....OO..O
.OO........O.......O........OO.
.....O......O.....O......O.....
.....OO.................OO.....
......O.................O......
...............O...............
...OOO........O.O........OOO...
..O......OOO.O...O.OOO......O..
..OO.....O.OOO...OOO.O.....OO..
O.......O.............O.......O
..OOO.O.OO...........OO.O.OOO..
........OO...........OO........
OOO.OO..O..O.......O..O..OO.OOO
.......O....OO...OO....O.......
.....O...................O.....
.......O.O...........O.O.......
..........O.........O..........
........O.............O........
.........O...........O.........
"""


def create_pattern():
    return pattern
